name: CI for stripe-samples/terminal
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'

env:
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - server_type: ruby
            server_image: ruby:3.0
          - server_type: ruby
            server_image: ruby:2.6
          - server_type: node
            server_image: node:14.17
          - server_type: node
            server_image: node:12.22
          - server_type: python
            server_image: python:3.9
          - server_type: python
            server_image: python:3.6
          - server_type: java
            server_image: maven:3.8-openjdk-16
          - server_type: java
            server_image: maven:3.8-openjdk-8
          - server_type: go
            server_image: golang:1.16
          - server_type: go
            server_image: golang:1.15
          - server_type: dotnet
            server_image: mcr.microsoft.com/dotnet/sdk:6.0
        target:
          - sample: server-driven
            tests: server_spec.rb

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'

      - name: Setup dependencies
        run: |
          source sample-ci/helpers.sh
          setup_dependencies

      - name: Run tests
        run: |
          source sample-ci/helpers.sh

          install_docker_compose_settings
          export STRIPE_WEBHOOK_SECRET=$(retrieve_webhook_secret)

          configure_docker_compose_for_integration "${{ matrix.target.sample }}" "${{ matrix.runtime.server_type }}" ../../client "${{ matrix.runtime.server_image }}"

          docker-compose up -d && wait_web_server
          docker-compose exec -T runner bundle exec rspec spec/${{ matrix.target.tests }}

      - name: Collect debug information
        if: ${{ failure() }}
        run: |
          cat .env
          cat docker-compose.yml
          docker-compose ps -a
          docker-compose logs web
